networks:
  redpanda_network:
    driver: bridge
    ipam:
      config:
      - subnet: 172.24.1.0/24
        gateway: 172.24.1.1
services:
  redpanda:
    command:
      - redpanda
      - start
      - --node-id 0
      - --smp 1
      - --memory 1G
      - --overprovisioned
    image: docker.vectorized.io/vectorized/redpanda:v21.12.1-wasm-beta1
    container_name: redpanda
    networks:
      redpanda_network:
        ipv4_address: 172.24.1.2
    volumes:
      - ./redpanda-wasm.yaml:/etc/redpanda/redpanda.yaml
    ports:
      - 8081:8081  # Schema registry port
      - 8082:8082 # Pandaproxy port
      - 9092:9092 # Kafka API port
      - 9644:9644  # Prometheus and HTTP admin port
