networks:
  redpanda_network:
    driver: bridge
    ipam:
      config:
      - subnet: '172.24.1.0/24'
        gateway: '172.24.1.1'
services:
  spark-master:
    image: docker.io/bitnami/spark:3
    container_name: 'spark-master'
    networks:
      redpanda_network:
        ipv4_address: '172.24.1.2'
    environment:
      - SPARK_MODE=master
      - SPARK_LOCAL_IP=spark-master
    ports:
      - '7077:7077'
      - '8080:8080'
  spark-worker:
    image: docker.io/bitnami/spark:3
    container_name: 'spark-worker'
    networks:
      redpanda_network:
        ipv4_address: '172.24.1.3'
    environment:
      - SPARK_MODE=worker
      - SPARK_LOCAL_IP=spark-worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_WEBUI_PORT=8081
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    ports:
      - '8081:8081'
  redpanda:
    command:
      - redpanda
      - start
      - --node-id
      - '0'
      - --kafka-addr
      - 'internal://0.0.0.0:9092,external://172.24.1.4:19092'
      - --advertise-kafka-addr
      - 'internal://172.24.1.4:9092,external://127.0.0.1:19092'
      - --rpc-addr
      - '172.24.1.4:33145'
      - --advertise-rpc-addr
      - '172.24.1.4:33145'
      - --smp 1
      - --memory 1G
      - --overprovisioned
      - --check=false
    image: 'docker.vectorized.io/vectorized/redpanda:latest'
    container_name: 'redpanda'
    networks:
      redpanda_network:
        ipv4_address: '172.24.1.4'
    ports:
      - '19092:19092'
